### ISSUE TITLE
proper_driver = console_cmd(r'reg query HKLM\HARDWARE\DEVICEMAP\SERIALCOMM')

### ISSUE THREAD

**Issue by ligteltelecom** [bkerler/edl#178] opened 2021-10-30 12:38 UTC
Hi
How to solve this issue? 
```
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
Traceback (most recent call last):
  File "D:\edlnew\edl", line 362, in <module>
    base.run()
  File "D:\edlnew\edl", line 218, in run
    proper_driver = console_cmd(r'reg query HKLM\HARDWARE\DEVICEMAP\SERIALCOMM')
  File "D:\edlnew\edl", line 153, in console_cmd
    output = read.stdout.read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 17: invalid continuation byte
O thread 0x3480 foi fechado com o código 0 (0x0).
```

**Comment by bkerler** [comment] 2021-12-05 13:59
Duplicate of #162

**Closed by bkerler** 2021-12-05 13:59 UTC
