### ISSUE TITLE
Instantanious write to OnePlus 9

### ISSUE THREAD

**Issue by ElRoberto538** [bkerler/edl#122] opened 2021-08-08 02:47 UTC
When trying to write a backup to my OnePlus 9  it succeeds instantaneously (but doesn't actually write anything). Any ideas? Dumping the partitions worked fine.

./edl.py --loader=Loaders/oneplus/0000000000514d67_a26bc25799770106_fhprg_op9.bin wl dumps --memory=ufs --lun=0

Qualcomm Sahara / Firehose Client V3.5 (c) B.Kerler 2018-2021.
main - Using loader Loaders/oneplus/0000000000514d67_a26bc25799770106_fhprg_op9.bin ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
firehose - Chip serial num: 2661799270 (0x9ea7d566)
firehose - Supported Functions: program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest
firehose - 
firehose - TargetName=
firehose - MemoryName=UFS
firehose - Version=
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest
oneplus - Oneplus protection with prjid 18821 detected
Writing dumps/lun0/carrier.bin to partition carrier.
firehose - 
Writing to physical partition 0, sector 18440, sectors 16384
Writing dumps/lun0/opluslog.bin to partition opluslog.
firehose - 
Writing to physical partition 0, sector 34824, sectors 65536
Writing dumps/lun0/persist.bin to partition persist.
firehose - 
Writing to physical partition 0, sector 2056, sectors 8192
Writing dumps/lun0/vbmeta_system_b.bin to partition vbmeta_system_b.
firehose - 
Writing to physical partition 0, sector 108568, sectors 16
Writing dumps/lun0/oplusstanvbk_a.bin to partition oplusstanvbk_a.
firehose - 
Writing to physical partition 0, sector 13320, sectors 2560
Writing dumps/lun0/vbmeta_system_a.bin to partition vbmeta_system_a.
firehose - 
Writing to physical partition 0, sector 108552, sectors 16
Writing dumps/lun0/vbmeta_vendor_b.bin to partition vbmeta_vendor_b.
firehose - 
Writing to physical partition 0, sector 108600, sectors 16
Writing dumps/lun0/ssd.bin to partition ssd.
firehose - 
Writing to physical partition 0, sector 6, sectors 2
Writing dumps/lun0/frp.bin to partition frp.
firehose - 
Writing to physical partition 0, sector 10632, sectors 128
Writing dumps/lun0/rawdump.bin to partition rawdump.
firehose - 
Writing to physical partition 0, sector 112712, sectors 32768
Writing dumps/lun0/misc.bin to partition misc.
firehose - 
Writing to physical partition 0, sector 10248, sectors 256
Writing dumps/lun0/super.bin to partition super.
firehose - 
Writing to physical partition 0, sector 145480, sectors 2732032
Writing dumps/lun0/keystore.bin to partition keystore.
firehose - 
Writing to physical partition 0, sector 10504, sectors 128
Writing dumps/lun0/metadata.bin to partition metadata.
firehose - 
Writing to physical partition 0, sector 108616, sectors 4096
Writing dumps/lun0/oplusstanvbk_b.bin to partition oplusstanvbk_b.
firehose - 
Writing to physical partition 0, sector 15880, sectors 2560
Writing dumps/lun0/userdata.bin to partition userdata.
firehose - 
Writing to physical partition 0, sector 2877512, sectors 58007475
Writing dumps/lun0/param.bin to partition param.
firehose - 
Writing to physical partition 0, sector 8, sectors 2048
Writing dumps/lun0/persist_bkp.bin to partition persist_bkp.
firehose - 
Writing to physical partition 0, sector 100360, sectors 8192
Writing dumps/lun0/oplusdycnvbk.bin to partition oplusdycnvbk.
firehose - 
Writing to physical partition 0, sector 10760, sectors 2560
Writing dumps/lun0/vbmeta_vendor_a.bin to partition vbmeta_vendor_a.
firehose - 
Writing to physical partition 0, sector 108584, sectors 16

**Comment by bkerler** [comment] 2021-08-08 08:39
That means that oneplus might have changed the way the write is authenticated on oneplus 9.

**Comment by ElRoberto538** [comment] 2021-08-28 01:06
Thanks for looking into this. How do I use the correct projectid for the OnePlus 9? Am I using the wrong loader?

**Comment by bkerler** [comment] 2021-08-28 11:00
Did you at some time use any patched msmdownloadtool ? Your param is broken (clearly one from oneplus 7 pro) and you might have a paperweight now. What op 9 do you have ? Regular, pro ? T-mobile ?

**Comment by ElRoberto538** [comment] 2021-08-29 01:50
Oh weird, I haven't run any MSM tool on it, only edl to do memory/storage dumps. I did actually manage to fix it though. It was stuck in a bootloop, after a decent amount of attempts (no exaggeration, at least 50) I managed to time the key combo just right to get it to drop back into fastboot so I could reflash the partitions. It's the regular op9 with 12g RAM, I'm working with some others to port postmarketos to it.

**Comment by amingin** [comment] 2021-11-11 18:02
Yesterday I had to use the whole package to unbrick from the paperweight state. Initially, it behaved the same way as described in this issue. The reason was that somehow prjid is not correctly set when oneplus class is created (prjid is "" in __init__, though, not None). It results in token being incorrectly generated and devices returns failed validation. So, when correct prjid is hardcoded in __init__, everything works. I didn't go further as to why that happens, though.

On another matter (not directly related, discovered while unbricking), OnePlus changed XML format a bit for QFIL, it's now <Image> tag inside <program> tag with actual filename (from settings.xml in OPS file), not in <program> tag itself... Though worth mentioning for people trying to return their devices from the dead.

**Comment by bkerler** [comment] 2021-11-11 21:53
for devices where param is messed up, prjid (devicemodel) isn't recognized correctly, then you need to use the devicemodel option with the right prjid

**Comment by bkerler** [comment] 2021-11-14 17:55
Closing this issue now as op9 is now confirmed to work fine.

**Closed by bkerler** 2021-11-14 17:55 UTC
Labels: enhancement
