### ISSUE TITLE
EDLAuth

### ISSUE THREAD

**Issue by dgmarie** [bkerler/edl#119] opened 2021-08-01 21:28 UTC
I'm trying to unbrick a Xiaomi Mi 9t with a missing system partition.

I ran ./edl.py printgpt --memory=ufs --loader=prog_ufs_firehose_sdm855_ddr.elf

I got: 

HWID:              0x000e60e100720000 (MSM_ID:0x000e60e1,OEM_ID:0x0072,MODEL_ID:0x0000)
CPU detected:      "SM7150"
PK_HASH:           0x1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda46
Serial:            0x3cca0979

sahara - Uploading loader prog_ufs_firehose_sdm855_ddr.elf ...
Successfully uploaded programmer :)
firehose - Nop succeeded.
firehose - INFO: Chip serial num: 1019873657 (0x3cca0979)
firehose - Supported Functions: program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt
firehose - 
firehose_client - Target detected: SM7150
firehose - Xiaomi EDL Auth detected.
Traceback (most recent call last):
  File "/home/dgmarie/edl/./edl.py", line 368, in <module>
    base.run()
  File "/home/dgmarie/edl/./edl.py", line 346, in run
    fh = firehose_client(args, self.cdc, self.sahara, self.__logger.level, print)
  File "/home/dgmarie/edl/Library/firehose_client.py", line 99, in __init__
    if self.firehose.configure(0):
  File "/home/dgmarie/edl/Library/firehose.py", line 799, in configure
    if self.modules.edlauth():
AttributeError: 'NoneType' object has no attribute 'edlauth'

Not sure if I'm doing something wrong or if it's a problem with the tool, I saw that a similar issue was closed.

**Comment by dgmarie** [comment] 2021-08-01 21:30
Looks like this is a known bug actually

**Comment by bkerler** [comment] 2021-08-02 15:18
fixed with commit 55bbfa43ff5baaf50c40623d3e59f478992f63ac

**Comment by bkerler** [comment] 2021-08-02 15:19
Duplicate of issue #115

**Closed by bkerler** 2021-08-02 15:19 UTC
Labels: bug
